# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_examplerust_wrappers", use_symbols = TRUE, package_name = "examplerust")

#' @docType package
#' @usage NULL
#' @useDynLib examplerust, .registration = TRUE
NULL

#' Calculate Euclidean distance matrix
#' @export
euclidean_dist <- function(a) .Call(wrap__euclidean_dist, a)

